// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.QRCodeReader
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("topLeft")]
        public BottomLeft TopLeft { get; set; }

        [JsonProperty("topRight")]
        public BottomLeft TopRight { get; set; }

        [JsonProperty("bottomLeft")]
        public BottomLeft BottomLeft { get; set; }

        [JsonProperty("bottomRight")]
        public BottomLeft BottomRight { get; set; }
    }

    public partial class BottomLeft
    {
        [JsonProperty("x")]
        public double X { get; set; }

        [JsonProperty("y")]
        public double Y { get; set; }
    }
}
